char* color_names[] = {
  "Oxford Blue",
  "Duke Blue",
  "Blue",
  "Dark Green",
  "Midnight Green",
  "Cobalt Blue",
  "Blue Moon",
  "Islamic Green",
  "Jaeger Green",
  "Tiffany Blue",
  "Vivid Cerulean",
  "Green",
  "Malachite",
  "Medium Spring Green",
  "Cyan",
  "Bulgarian Rose",
  "Imperial Purple",
  "Indigo",
  "Electric Ultramarine",
  "Army Green",
  "Liberty",
  "Very Light Blue",
  "Kelly Green",
  "May Green",
  "Cadet Blue",
  "Picton Blue",
  "Bright Green",
  "Screamin' Green",
  "Medium Aquamarine",
  "Electric Blue",
  "Dark Candy Apple Red",
  "Jazzberry Jam",
  "Purple",
  "Vivid Violet",
  "Windsor Tan",
  "Rose Vale",
  "Purpureus",
  "Lavender Indigo",
  "Limerick",
  "Brass",
  "Baby Blue Eyes",
  "Spring Bud",
  "Inchworm",
  "Mint Green",
  "Celeste",
  "Red",
  "Folly",
  "Fashion Magenta",
  "Magenta",
  "Orange",
  "Sunset Orange",
  "Brilliant Rose",
  "Shocking Pink",
  "Chrome Yellow",
  "Rajah",
  "Melon",
  "Rich Brilliant Lavender",
  "Yellow",
  "Icterine",
  "Pastel Yellow",
};
